all:
  hosts:
    its-21c4:
      ansible_host: its-nas-c4.acs.sh

pihole:
  hosts:
    its-pihole-c1:
      ansible_host: its-pi-c1.acs.sh
      
    its-pihole-c2:
      ansible_host: its-pi-c2.acs.sh
